---
- name: Delete AWS EC2 server
  ec2:
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    state: absent
    instance_ids: i-091ad50c8881f7698
  register: ec2

- name: Print all EC2 variables
  debug:
    var: ec2
