---
# ------COPY NEW SETTINGS.PY WITH S3 PARAMETERS------
- name: copy new settings.py with S3 parameters
  copy: src=settings.py dest={{ dest_dir }}

# ------STOP CONTAINERS------
- name: Stop containers
  shell: docker-compose -f django_pgsql_nginx_docker/docker-compose.yml down -v

# ------REBUILD AND START CONTAINERS------
- name: Rebuild and start containers
  shell: docker-compose -f django_pgsql_nginx_docker/docker-compose.yml up -d --build

# ------COLLECT STATIC IN WEB CONTAINER------
- name: Collect static in container
  shell: docker exec django_pgsql_nginx_docker_web_1 python3.7 web_trial/manage.py collectstatic --no-input
