---
# ------INSTALL PLUGIN FOR ANSIBLE------
- name: Install ansible plugin localy 
  shell: ansible-galaxy collection install amazon.aws

# ------CREATE S3------
- name: Create S3 bucket
  amazon.aws.aws_s3:
    bucket: koval.crm.django
    mode: create
    permission: public-read
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: s3

# ------DEBUG------
- name: Debug
  debug:
    var: s3
